- branch: main
  protection:
    required_status_checks:
      strict: true
      contexts:
        - test
        - build
    required_pull_request_reviews:
      dismissal_restrictions: null
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
      required_approving_review_count: 1
    required_linear_history: false
    allow_force_pushes: true
    allow_deletions: false